### ISSUE TITLE
下載檔案程式自動關閉

### ISSUE THREAD

**Issue by ChinaGon** [EndlessMISAKA/AtelierMisaka#23]
大大您好

非常感謝您開發的這個程式

讓我們不用一直右鍵下載保存圖片或影片

在使用後有發現一個問題

https://fantia.jp/fanclubs/18/

這位作者

我有訂閱他2500的會員

下載到1/23的資料後

程式就會自動關閉

試了好幾次都這樣

如果有需要

我可以提供cookies給您測試

感謝^^

**Comment by EndlessMISAKA** [comment]
啊，抱歉，最近几天要准备考试没有看github。
自动关闭的话，windows开始菜单中搜索一下“事件查看器”，其中“windows日志”→“应用程序”里面，在自动关闭的时间点会有两个错误，把来源是“.Net runtime”的那个错误内容复制出来看看。

**Comment by ChinaGon** [comment]
Application: AtelierMisaka.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at AtelierMisaka.Models.DownloadItem.<Start>b__65_0()
   at System.Threading.Tasks.Task`1[[AtelierMisaka.ErrorType, AtelierMisaka, Version=1.5.2.0, Culture=neutral, PublicKeyToken=null]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at AtelierMisaka.Models.DownloadItem+<Start>d__65.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

感謝大大您的回應

**Comment by EndlessMISAKA** [comment]
嗷，这可能要用你的cookies来调节了，不过我这周六就要考试了，可以等到周日以后吗？

**Comment by ChinaGon** [comment]
等大大有時間再處理就可以了

感謝大大

祝福大大考試順利!

**Comment by EndlessMISAKA** [comment]
谢谢祝福（能把作文写完就算顺利
有什么聊天工具的联系方式吗？QQ或者discord？
cookies短时间内会持续有效，所以会有泄漏的风险，最好不要直接发在网站里

**Comment by ChinaGon** [comment]
您好

我有用discord

@ChinaGon

感謝您

**Comment by EndlessMISAKA** [comment]
好的，我创建了一个服务器
https://discord.gg/4M7s3KyE
来这里聊聊吧_(:3ゝ∠)_
不过我没怎么用过discord...
