### ISSUE TITLE
AtelierMisaka.exe closes/crashes immediately after clicking "ok"

### ISSUE THREAD

**Issue by shmepzoher** [EndlessMISAKA/AtelierMisaka#31]
x64 browswer is installed in the folder so the main .exe is opening properly, but after inputting the parameters it crashes after I click "ok". 

The "Update SupporList" button also doesn't seem to actually do anything after cookies are entered. It will load for about a second and then say 'Post Count: 0"

**Comment by shmepzoher** [comment]
This is the error log...

9/1/2021 1:42:04 PM
The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at AtelierMisaka.FanboxUtils.GetWebCode(String url, String referer, String orig)
   at AtelierMisaka.FanboxUtils.<GetArtistList>b__6_0()

**Comment by EndlessMISAKA** [comment]
It seems web request is faild. 
About the crashes bug, open the "Event Viewer" in Windows Start Menu. Look at "Windows logs → Application" and Find Error about AtelierMisaka.exe (type: .NET Runtime), copy the Infomation to tell me.

The "Update SupptorList" button will get all illustrators who you are supportted and fill into combobox "Url".
It will say "Post Count: 0", please ignore it.

**Comment by shmepzoher** [comment]
Application: AtelierMisaka.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DllNotFoundException
   at SQLite.SQLite3.LibVersionNumber()
   at SQLite.SQLiteConnection..ctor(SQLite.SQLiteConnectionString)
   at AtelierMisaka.SQLiteConnectionFactory.GetConnection()
   at AtelierMisaka.SQLiteDownloadLogHelper..ctor()
   at AtelierMisaka.SQLiteDownloadLogHelper.get_Instance()
   at AtelierMisaka.Models.DownloadLogList..ctor()
   at AtelierMisaka.GlobalMethord.Init()

Exception Info: System.Windows.Markup.XamlParseException
   at System.Windows.Markup.XamlReader.RewrapException(System.Exception, System.Xaml.IXamlLineInfo, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at AtelierMisaka.App.Main()

**Comment by EndlessMISAKA** [comment]
please confirm "sqlite3.dll" is put in "x64" or "x86" folder.

**Comment by shmepzoher** [comment]
It is

**Comment by EndlessMISAKA** [comment]
"x64" or "x86" folder is put in soft folder? 
for example:
"D:\AtelierMisaka\x64" + "D:\AtelierMisaka\AtelierMisaka.exe" is right.
"D:\AtelierMisaka\AtelierMisaka_Browser_x64\x64" + "D:\AtelierMisaka\AtelierMisaka.exe" is error.

**Comment by shmepzoher** [comment]
Yes, that is how I have it. 

Prior to those being in the correct folder AtelierMisaka.exe wouldn't even open.

**Comment by EndlessMISAKA** [comment]
emmm, I will upload a test version, you can run it, and send the "error.log" to me

**Comment by shmepzoher** [comment]
From the V1.5.13.1 version

------------------
9/3/2021 10:52:24 AM
System.IO.FileLoadException: Could not load file or assembly 'CefSharp.Wpf, Version=79.1.360.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'CefSharp.Wpf, Version=79.1.360.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at AtelierMisaka.Views.Pop_Setting.<Btn_Star_Click>d__16.MoveNext()
   at System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at AtelierMisaka.Views.Pop_Setting.Btn_Star_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at AtelierMisaka.App.Main()

**Comment by EndlessMISAKA** [comment]
it look like security problem.
Try opening the dll file "CefSharp.Wpf.dll" properties and clicking 'Unblock':
https://i.stack.imgur.com/eaElA.png

**Comment by shmepzoher** [comment]
What's a good program for opening it? My computer just defaults to notepad.

**Comment by EndlessMISAKA** [comment]
select file and click rightMouseButton, select "properties"

**Comment by shmepzoher** [comment]
That seems to have fixed it!
